name: "Nile-pgvector-reuse"
implementation: "pgvector"
build_params:
  connection_params:
    host: "us-west-2.db.dev.thenile.dev"
    port: 5432
    database: "dedicated_new"
    user: "0197f6a3-3337-775d-83cd-f5da818c10b8"
    password: "5a46ff30-d6fd-485b-9ada-4c3f826afb1e"
  table_name: "vectors"
  index_name: "vectors_hnsw_idx"
  tenant_id: "0197f6a3-3337-775d-83cd-f5da818c10b8"  # Use the user UUID as tenant ID
  batch_size: 1000
  m: 16
  ef_construction: 64
  reuse_table: true  # Skip data loading and index creation, use existing table
search_params:
  ef: 100
supports_concurrent_insert: true
supports_incremental_build: true 