# 1M vector benchmark configuration
dataset_size: 1000000
query_count: 10000
dataset_path: null  # Use synthetic data

dataset_generation:
  enabled: true
  # Ground truth computation block sizes (for memory management) - REQUIRED
  gt_train_block_size: 50000  # 50K vectors for 1M dataset
  gt_query_block_size: 1000  # 1000 queries for efficient processing
  # Dataset generation parameters
  dimension: 128
  clusters: 100
  cluster_std: 0.15
  k_neighbors: 100
  seed: 42

concurrent_inserters: 4
concurrent_searchers: 8
search_batch_size: 50
insert_batch_size: 1000
max_runtime_seconds: 300