# 1K vector benchmark for testing
# Dataset Mode: GENERATE_SYNTHETIC
dataset_size: 1000
query_count: 100

## Save smol data for laterz
dataset_path: "datasets/synthetic_1k_64dim.h5"
# No dataset_path specified - will generate synthetic data
dataset_generation:
  enabled: true
  dimension: 64
  clusters: 10
  cluster_std: 0.1
  k_neighbors: 10
  seed: 42

concurrent_inserters: 0
concurrent_searchers: 2
search_batch_size: 5
insert_batch_size: 50
max_runtime_seconds: 30
benchmark_mode: "search_only"

# Hybrid mode settings (used when benchmark_mode is "hybrid")
initial_build_percentage: 10
initial_build_size_cap: 100

output_path: "results/"
recall_targets: [0.9, 0.95, 0.99] 