# 1M vector benchmark configuration
dataset_size: 1000000
query_count: 10000
dataset_path: null  # Use synthetic data

dataset_generation:
  enabled: true
  dimension: 128
  clusters: 100
  cluster_std: 0.15
  k_neighbors: 100
  seed: 42

concurrent_inserters: 4
concurrent_searchers: 8
search_batch_size: 50
insert_batch_size: 1000
max_runtime_seconds: 300
warmup_seconds: 30
output_path: "results/"
recall_targets: [0.9, 0.95, 0.99]