# Small 10K vector benchmark for testing hybrid mode with larger initial batch
dataset_size: 10000
query_count: 1000
dataset_path: null  # Use synthetic data

dataset_generation:
  enabled: true
  dimension: 128
  clusters: 5
  cluster_std: 0.2
  k_neighbors: 100
  seed: 42

concurrent_inserters: 2
concurrent_searchers: 4
search_batch_size: 10
insert_batch_size: 100
max_runtime_seconds: 60
benchmark_mode: "hybrid"  # "search_only" or "hybrid"

# Hybrid mode settings with larger initial batch
initial_build_percentage: 25  # 25% of dataset to build initially
initial_build_size_cap: 5000  # Higher cap for larger initial builds