# 100M vector benchmark configuration
dataset_size: 100000000
query_count: 1000000
dataset_path: null  # Use synthetic data

dataset_generation:
  enabled: true
  distribution: "mixed"  # Mix of clustered and uniform data
  dimension: 128
  clusters: 10000
  cluster_std: 0.1
  k_neighbors: 100
  seed: 42

concurrent_inserters: 16
concurrent_searchers: 32
search_batch_size: 100
insert_batch_size: 10000
max_runtime_seconds: 1800  # 30 minutes
warmup_seconds: 60
output_path: "results/"
recall_targets: [0.9, 0.95, 0.99]